apiVersion: apps/v1
kind: Deployment
metadata:
  name: skuum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sku
  template:
    metadata:
      labels:
        app: sku
    spec:
      containers:
      - name: sku
        image: carlosrjdc/app:lasted
        ports:
        - containerPort: 3000 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skudois
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sku
  template:
    metadata:
      labels:
        app: sku
    spec:
      containers:
      - name: sku
        image: carlosrjdc/app:lasted
        ports:
        - containerPort: 3000 
---

apiVersion: v1
kind: Service
metadata:
  name: sku-service
spec:
  selector:
    app: sku  # Rótulo do Pod que o Service deve direcionar o tráfego
  ports:
    - protocol: TCP
      port: 80  # Porta exposta pelo Service
      targetPort: 3000  # Porta na qual o contêiner do Pod está ouvindo
  type: ClusterIP  # Tipo de Service (ClusterIP é o padrão)