apiVersion: apps/v1
kind: Deployment
metadata:
  name: skuum
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sku
  template:
    metadata:
      labels:
        app: sku
    spec:
      containers:
      - name: sku
        image: sku
        ports:
        - containerPort: 3000 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skudois
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sku
  template:
    metadata:
      labels:
        app: sku
    spec:
      containers:
      - name: sku
        image: sku
        ports:
        - containerPort: 3000 


