apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: sku
  newName: carlosrjdc/app
  newTag: abd62a3ac39eb34af94c17014e8a9bffe14e4491
- name: suk
  newName: carlosrjdc/app
  newTag: 55f36cb53adbe095908594b2a2a67c54317ce556
