apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: sku
  newName: carlosrjdc/app
  newTag: e1f6ae0d3fc3f24c0764edd0f148568d84c38ca1
