apiVersion: v1
kind: Service
metadata:
  name: sku-service
  namespace: default
spec:
  selector:
    app: sku  # Rótulo do Pod que o Service deve direcionar o tráfego
  ports:
    - protocol: TCP
      port: 80  # Porta exposta pelo Service
      targetPort: 3000  # Porta na qual o contêiner do Pod está ouvindo
  type: ClusterIP  # Tipo de Service (ClusterIP é o padrão)